apiVersion: v1
kind: Service
metadata:
  name: {{ include "dealbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dealbot.name" . }}
    helm.sh/chart: {{ include "dealbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "dealbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
